#
# Copyright 2020 isobar. All Rights Reserved.
#
# The isobar node image
#
# Usage:
#       docker build -t isobar/node:1.0.0 -f Dockerfile .
#

#FROM node:12
#FROM node:12-alpine
FROM isobar/node:12-alpine
#FROM isobar/node:12-alpine-gm
#FROM mcr.microsoft.com/vscode/devcontainers/javascript-node:12

LABEL maintainer "jacky.huang@isobar.com"

WORKDIR /workspace

# install dev tools
#RUN apk --no-cache add curl git openssl subversion

#COPY . .
#RUN npm install

# Define default command.
#CMD ["npm", "start"]
#CMD ["pm2-runtime", "-V"]
#CMD ["pm2-runtime", "start", "pm2.json"]
