version: '3'
services:
  app:
    #user: node
    #build:
    #  context: .
    #  dockerfile: Dockerfile

    image: isobartw/node:12-alpine

    volumes:
      - node-test1-volume:/workspace
    # Overrides default command so things don't shut down after the process end.
    command: sleep infinity
    
    links:
      - mongo

  mongo:
    image: mongo
    restart: unless-stopped
    volumes:
      - mongo-test-volume:/data/db

volumes:
  node-test1-volume:
  mongo-test-volume: